spring:
  output:
    ansi:
      enabled: ALWAYS
otel:
  traces:
    exporter: logging
  metrics:
    exporter: none
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  service:
    name: otel-gateway-api
